commerce_payment.commerce_payment_gateway.plugin.commerce_xaigate:
  type: commerce_payment_gateway_configuration
  mapping:
    apikey:
      type: string
      label: 'API key'
    shopname:
      type: string
      label: 'Shop name'
   
